CREATE TABLE IF NOT EXISTS `b_realposterum_ai_task` (
    `ID` int unsigned NOT NULL AUTO_INCREMENT,
    `PRODUCT_ID` int unsigned NOT NULL,
    `SOURCE_IBLOCK_ID` int unsigned NOT NULL,
    `STATUS` varchar(32) NOT NULL DEFAULT 'QUEUED',
    `IDEMPOTENCY_KEY` varchar(64) NOT NULL,
    `REQUEST_METHOD` varchar(8) DEFAULT NULL,
    `ENDPOINT` varchar(255) DEFAULT NULL,
    `REQUEST_HEADERS_JSON` longtext DEFAULT NULL,
    `SOURCE_SNAPSHOT_JSON` longtext NOT NULL,
    `MAPPED_PAYLOAD_JSON` longtext NOT NULL,
    `REQUEST_BODY` longtext DEFAULT NULL,
    `RESPONSE_BODY` longtext DEFAULT NULL,
    `PARSED_DATA_JSON` longtext DEFAULT NULL,
    `SELECTED_FIELDS_JSON` longtext DEFAULT NULL,
    `ERROR_MESSAGE` text DEFAULT NULL,
    `CREATED_AT` datetime NOT NULL,
    `UPDATED_AT` datetime NOT NULL,
    `LAST_ATTEMPT_AT` datetime DEFAULT NULL,
    `RESPONSE_RECEIVED_AT` datetime DEFAULT NULL,
    `APPLIED_AT` datetime DEFAULT NULL,
    `REJECTED_AT` datetime DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `ix_realposterum_ai_task_status` (`STATUS`),
    KEY `ix_realposterum_ai_task_product` (`PRODUCT_ID`, `SOURCE_IBLOCK_ID`),
    KEY `ix_realposterum_ai_task_idempotency` (`IDEMPOTENCY_KEY`)
);

CREATE TABLE IF NOT EXISTS `b_realposterum_ai_log` (
    `ID` int unsigned NOT NULL AUTO_INCREMENT,
    `TASK_ID` int unsigned DEFAULT NULL,
    `LOG_TYPE` varchar(50) NOT NULL,
    `LEVEL` varchar(16) NOT NULL,
    `MESSAGE` text DEFAULT NULL,
    `CONTEXT_JSON` longtext DEFAULT NULL,
    `CREATED_AT` datetime NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `ix_realposterum_ai_log_task` (`TASK_ID`, `ID`),
    KEY `ix_realposterum_ai_log_type` (`LOG_TYPE`)
);
